services:
  app:
    build:
      context: .devcontainer
      dockerfile: dockerfile.devcontainer
      # args: 
      #   - USER=${USER_NAME}
      #   - UID=${UID}
    # network_mode: host
    extra_hosts:
      - "localhost:host-gateway"
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban_password
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  