FROM node:24.2.0-bookworm

# ARG USER
# ARG UID
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    curl \
    gnupg \
    jq \
    unzip
RUN npm install -g @anthropic-ai/claude-code

USER node

# Install Bun for node user
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/home/node/.bun/bin:$PATH"